# Lecture 4

In [2]:
# Lambda functions

# one argument case
add_ten = lambda x: x + 10
print(add_ten(89))

99


In [6]:
# multiple arguments
calc = lambda x, y: (x-y, x**y)
print(calc(8, 2))

# So it comes out as a tuple

(6, 64)


In [12]:
# with conditional logic
check = lambda x: "Positive" if x > 0 else "Negative" if x < 0 else "Zero"
check2 = lambda x: "Zero" if x == 0 else "Non-zero"

print(check(0))
print(check2(1))
print(check2(0))

Zero
Non-zero
Zero


In [17]:
# Example: map a list of numbers to a list of the squares of the numbers
nums = [1,2,3,4]

# You need the map function. It applies a specified function to each item of an iterable.
# Returns a "lazy" iterator (a map object) containing the transformed results
squares = list(map(lambda x: x**2, nums))
print(squares)

[1, 4, 9, 16]


In [ ]:
# Functions

def power(x, y):
    return x**y

In [8]:
# Miscellaneous
import numpy as np

A = np.zeros((5,5))
print(A)

big_matrix = []

for i in range(0, 5):
    row = []
    for j in range(0, 5):
        row.append(0)

    big_matrix.append(row) 

print(big_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
