# Backward Substitution

In [36]:
# Page 46
import numpy as np

# 0-index, 0, 1, 2
A = np.array([
    [1,0,3],
    [0,2,4],
    [0,0,1]
])

# Let n be the legnth of A
n = len(A)

# Initialize the x's with 0s
x = np.zeros(3)

# Let b be the solutions
b = np.array([1,2,3])

# To maintain 0 intex, subtract 1 from n
# In this example, let n = 3 for dimension 3. So, 3 - 1 = 2
# Remember that the end is exclusive, hence -1. So from 2 to 0
for i in range(n-1, -1, -1):

    print("Loop 1\n")
    # For the first iteration, let p equal the last value in b
    p = b[i]

    # From i to n, as the loop goes up the matrix, the loop goes for more
    # The first time it runs only once, the second time twice, and so on
    for j in range(i, n):
        print("Loop 2")
        p = p - A[i][j] * x[j]
    print()
    
    # This part is good. divide by diagonal
    x[i] = p / A[i][i]

print(x)

# To check, use x to matrix multiply with A

answer = A @ x

print(f"The answer from back substitution algorithm: {answer}")
print(f"Original b = {b}")

Loop 1

Loop 2

Loop 1

Loop 2
Loop 2

Loop 1

Loop 2
Loop 2
Loop 2

[-8. -5.  3.]
The answer from back substitution algorithm: [1. 2. 3.]
Original b = [1 2 3]


In [38]:

def backward_substitution(A, x, b):

    n = len(A)

    for i in range(n-1,-1,-1):
        p=b[i]
        for j in range(i,n):
            p=p-A[i][j] * x[j]
        x[i] = p / A[i][i]
    
    return x

# Tests

A = np.array([
    [6,-2,2,4],
    [0,-4,2,2],
    [0,0,2,-5],
    [0,0,0,-3]
])

# Initialize the x's with 0s
x = np.zeros(4)

# Let b be the solutions
b = np.array([16,-6,-9,-3])

print(backward_substitution(A, x, b))

[ 3.  1. -2.  1.]


# Gaussian Elimination with No Pivot (GEnoP)

In [56]:
# The idea is to turn the matrix A into a upper triangular matrix by continuously matrix multiplying it
# with versions of a "lower matrix". Get 0s under the pivots

def GEnoP(A, b):

    n = len(A)

    print(n)
    # Remember, 0 index, so range is different.
    # Original range is from 1 to n - 1.
    # This translates to 0 to n - 2
    for k in range(1, n-2):
        for i in range(k+1, n-1):
            A[i][k] = A[i][k] / A[k][k]

            for j in range (k + 1, n-1):
                A[i][j] = A[i][j] - A[i][k] * A[k][j]

            b[i] = b[i] - A[i][k] * b[k]
    
    return b

A = np.array([
    [6,-2,2,4],
    [12,-8,6,10],
    [3,-13,9,3],
    [-6,4,1,-18]
])

x = np.zeros(4)

b = np.array([16,26,-19,-34])

print(GEnoP(A, b))



4
[ 16  26 -45 -34]
